# Generated by Django 5.0.1 on 2024-05-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
